// Ghidra decompilation of librawbuf.so
// Auto-generated by headless DumpAll.java

// === FUN_00100880 @ 00100880 ===

void FUN_00100880(void)

{
  (*(code *)(undefined *)0x0)();
  return;
}



// === __cxa_finalize @ 001008a0 ===

void __cxa_finalize(void)

{
  __cxa_finalize();
  return;
}



// === malloc @ 001008b0 ===

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * malloc(size_t __size)

{
  void *pvVar1;
  
  pvVar1 = malloc(__size);
  return pvVar1;
}



// === memcpy @ 001008c0 ===

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * memcpy(void *__dest,void *__src,size_t __n)

{
  void *pvVar1;
  
  pvVar1 = memcpy(__dest,__src,__n);
  return pvVar1;
}



// === memset @ 001008d0 ===

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * memset(void *__s,int __c,size_t __n)

{
  void *pvVar1;
  
  pvVar1 = memset(__s,__c,__n);
  return pvVar1;
}



// === free @ 001008e0 ===

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void free(void *__ptr)

{
  free(__ptr);
  return;
}



// === __cxa_atexit @ 001008f0 ===

void __cxa_atexit(void)

{
  __cxa_atexit();
  return;
}



// === entry @ 00100900 ===

void entry(void)

{
  __cxa_finalize(&DAT_00112000);
  return;
}



// === FUN_0010090c @ 0010090c ===

void FUN_0010090c(code *param_1)

{
  if (param_1 != (code *)0x0) {
    (*param_1)();
  }
  return;
}



// === Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_allocate @ 0010093c ===

void Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_allocate
               (long *param_1,undefined8 param_2,int param_3)

{
  void *pvVar1;
  
  pvVar1 = malloc((long)param_3);
  if (pvVar1 != (void *)0x0) {
                    /* WARNING: Could not recover jumptable at 0x0010097c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    (**(code **)(*param_1 + 0x728))(param_1,pvVar1,(long)param_3);
    return;
  }
  return;
}



// === Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_release @ 0010098c ===

void Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_release
               (long *param_1,undefined8 param_2,undefined8 param_3)

{
  void *__ptr;
  
  __ptr = (void *)(**(code **)(*param_1 + 0x730))(param_1,param_3);
  if (__ptr != (void *)0x0) {
    free(__ptr);
    return;
  }
  return;
}



// === Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyPart @ 001009b8 ===

void Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyPart
               (long *param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4,int param_5,
               int param_6,int param_7)

{
  long lVar1;
  long lVar2;
  
  lVar1 = (**(code **)(*param_1 + 0x730))(param_1,param_3);
  lVar2 = (**(code **)(*param_1 + 0x730))(param_1,param_4);
  if ((lVar1 != 0) && (lVar2 != 0)) {
    memcpy((void *)(lVar1 + param_5),(void *)(lVar2 + param_6),(long)param_7);
    return;
  }
  return;
}



// === Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyByteArray @ 00100a48 ===

void Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyByteArray
               (long *param_1,undefined8 param_2,undefined8 param_3,int param_4,undefined8 param_5,
               int param_6,int param_7)

{
  int iVar1;
  int iVar2;
  int iVar3;
  void *__dest;
  long lVar4;
  
  __dest = (void *)(**(code **)(*param_1 + 0x730))(param_1,param_3);
  iVar2 = (**(code **)(*param_1 + 0x738))(param_1,param_3);
  lVar4 = (**(code **)(*param_1 + 0x5c0))(param_1,param_5,0);
  iVar3 = (**(code **)(*param_1 + 0x558))(param_1,param_5);
  iVar1 = iVar3 - param_6;
  if (param_7 <= iVar3 - param_6) {
    iVar1 = param_7;
  }
  iVar3 = iVar2 - param_4;
  if (iVar1 <= iVar2 - param_4) {
    iVar3 = iVar1;
  }
  memcpy(__dest,(void *)(lVar4 + param_6),(long)iVar3);
                    /* WARNING: Could not recover jumptable at 0x00100b28. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (**(code **)(*param_1 + 0x600))(param_1,param_5,lVar4,2);
  return;
}



// === Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyFloatArray @ 00100b2c ===

void Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyFloatArray
               (long *param_1,undefined8 param_2,undefined8 param_3,ulong param_4,undefined8 param_5
               ,int param_6,int param_7)

{
  ulong uVar1;
  int iVar2;
  int iVar3;
  long lVar4;
  long lVar5;
  
  lVar4 = (**(code **)(*param_1 + 0x730))(param_1,param_3);
  uVar1 = (param_4 & 0xffffffff) << 2;
  iVar2 = (**(code **)(*param_1 + 0x738))(param_1,param_3);
  lVar5 = (**(code **)(*param_1 + 0x5e8))(param_1,param_5,0);
  iVar3 = (**(code **)(*param_1 + 0x558))(param_1,param_5);
  iVar3 = (iVar3 - param_6) * 4;
  iVar2 = iVar2 - (int)uVar1;
  if (param_7 * 4 <= iVar3) {
    iVar3 = param_7 * 4;
  }
  if (iVar3 <= iVar2) {
    iVar2 = iVar3;
  }
  memcpy((void *)(lVar4 + (-((param_4 & 0xffffffff) >> 0x1f) & 0xfffffffc00000000 | uVar1)),
         (void *)(lVar5 + (long)param_6 * 4),(long)iVar2);
                    /* WARNING: Could not recover jumptable at 0x00100c18. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (**(code **)(*param_1 + 0x628))(param_1,param_5,lVar5,2);
  return;
}



// === Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyShortArray @ 00100c1c ===

void Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyShortArray
               (long *param_1,undefined8 param_2,undefined8 param_3,ulong param_4,undefined8 param_5
               ,int param_6,int param_7)

{
  ulong uVar1;
  int iVar2;
  int iVar3;
  long lVar4;
  long lVar5;
  
  lVar4 = (**(code **)(*param_1 + 0x730))(param_1,param_3);
  uVar1 = (param_4 & 0xffffffff) << 1;
  iVar2 = (**(code **)(*param_1 + 0x738))(param_1,param_3);
  lVar5 = (**(code **)(*param_1 + 0x5d0))(param_1,param_5,0);
  iVar3 = (**(code **)(*param_1 + 0x558))(param_1,param_5);
  iVar3 = (iVar3 - param_6) * 2;
  iVar2 = iVar2 - (int)uVar1;
  if (param_7 * 2 <= iVar3) {
    iVar3 = param_7 * 2;
  }
  if (iVar3 <= iVar2) {
    iVar2 = iVar3;
  }
  memcpy((void *)(lVar4 + (-((param_4 & 0xffffffff) >> 0x1f) & 0xfffffffe00000000 | uVar1)),
         (void *)(lVar5 + (long)param_6 * 2),(long)iVar2);
                    /* WARNING: Could not recover jumptable at 0x00100d08. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (**(code **)(*param_1 + 0x610))(param_1,param_5,lVar5,2);
  return;
}



// === Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyShortArrayOffset @ 00100d0c ===

void Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_copyShortArrayOffset
               (long *param_1,undefined8 param_2,undefined8 param_3,ulong param_4,undefined8 param_5
               ,int param_6,int param_7,short param_8)

{
  ulong uVar1;
  int iVar2;
  int iVar3;
  long lVar4;
  long lVar5;
  ulong uVar6;
  undefined8 *puVar7;
  short *__dest;
  ulong uVar8;
  undefined8 uVar9;
  undefined8 uVar10;
  undefined8 uVar11;
  undefined8 uVar12;
  
  lVar4 = (**(code **)(*param_1 + 0x730))(param_1,param_3);
  uVar1 = (param_4 & 0xffffffff) << 1;
  uVar8 = -((param_4 & 0xffffffff) >> 0x1f) & 0xfffffffe00000000 | uVar1;
  __dest = (short *)(lVar4 + uVar8);
  iVar2 = (**(code **)(*param_1 + 0x738))(param_1,param_3);
  lVar5 = (**(code **)(*param_1 + 0x5d0))(param_1,param_5,0);
  iVar3 = (**(code **)(*param_1 + 0x558))(param_1,param_5);
  iVar3 = (iVar3 - param_6) * 2;
  iVar2 = iVar2 - (int)uVar1;
  if (param_7 * 2 <= iVar3) {
    iVar3 = param_7 * 2;
  }
  if (iVar3 <= iVar2) {
    iVar2 = iVar3;
  }
  memcpy(__dest,(void *)(lVar5 + (long)param_6 * 2),(long)iVar2);
  if ((param_8 != 0) && (iVar3 = (int)((ulong)(long)iVar2 >> 1), 0 < iVar3)) {
    uVar1 = (ulong)(iVar3 - 1) + 1;
    if (uVar1 < 0x10) {
      uVar6 = 0;
    }
    else {
      uVar6 = uVar1 & 0x1fffffff0;
      if (uVar6 != 0) {
        __dest = __dest + uVar6;
        puVar7 = (undefined8 *)(lVar4 + uVar8 + 0x10);
        uVar8 = uVar6;
        do {
          uVar10 = puVar7[-1];
          uVar9 = puVar7[-2];
          uVar12 = puVar7[1];
          uVar11 = *puVar7;
          uVar8 = uVar8 - 0x10;
          puVar7[-1] = CONCAT26((short)((ulong)uVar10 >> 0x30) + param_8,
                                CONCAT24((short)((ulong)uVar10 >> 0x20) + param_8,
                                         CONCAT22((short)((ulong)uVar10 >> 0x10) + param_8,
                                                  (short)uVar10 + param_8)));
          puVar7[-2] = CONCAT26((short)((ulong)uVar9 >> 0x30) + param_8,
                                CONCAT24((short)((ulong)uVar9 >> 0x20) + param_8,
                                         CONCAT22((short)((ulong)uVar9 >> 0x10) + param_8,
                                                  (short)uVar9 + param_8)));
          puVar7[1] = CONCAT26((short)((ulong)uVar12 >> 0x30) + param_8,
                               CONCAT24((short)((ulong)uVar12 >> 0x20) + param_8,
                                        CONCAT22((short)((ulong)uVar12 >> 0x10) + param_8,
                                                 (short)uVar12 + param_8)));
          *puVar7 = CONCAT26((short)((ulong)uVar11 >> 0x30) + param_8,
                             CONCAT24((short)((ulong)uVar11 >> 0x20) + param_8,
                                      CONCAT22((short)((ulong)uVar11 >> 0x10) + param_8,
                                               (short)uVar11 + param_8)));
          puVar7 = puVar7 + 4;
        } while (uVar8 != 0);
        if (uVar1 == uVar6) goto LAB_00100e60;
      }
    }
    iVar3 = iVar3 - (int)uVar6;
    do {
      iVar3 = iVar3 + -1;
      *__dest = *__dest + param_8;
      __dest = __dest + 1;
    } while (iVar3 != 0);
  }
LAB_00100e60:
                    /* WARNING: Could not recover jumptable at 0x00100e90. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (**(code **)(*param_1 + 0x610))(param_1,param_5,lVar5,2);
  return;
}



// === Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_zeroDecodeArray @ 00100e94 ===

int Java_com_lumiyaviewer_rawbuffers_DirectByteBuffer_zeroDecodeArray
              (long *param_1,undefined8 param_2,undefined8 param_3,uint param_4,int param_5,
              undefined8 param_6,uint param_7,int param_8)

{
  byte bVar1;
  uint uVar2;
  int iVar3;
  bool bVar4;
  uint uVar5;
  uint uVar6;
  long lVar7;
  long lVar8;
  uint uVar9;
  ulong uVar10;
  ulong uVar11;
  
  lVar7 = (**(code **)(*param_1 + 0x5c0))(param_1,param_6,0);
  uVar5 = (**(code **)(*param_1 + 0x558))(param_1,param_6);
  lVar8 = (**(code **)(*param_1 + 0x5c0))(param_1,param_3,0);
  uVar6 = (**(code **)(*param_1 + 0x558))(param_1,param_3);
  if (param_8 + param_7 <= uVar5) {
    uVar5 = param_8 + param_7;
  }
  if (param_5 + param_4 <= uVar6) {
    uVar6 = param_5 + param_4;
  }
  uVar9 = param_4;
  if (param_7 < uVar5) {
    bVar4 = false;
    uVar11 = (ulong)param_7;
    do {
      uVar10 = (ulong)uVar9;
      bVar1 = *(byte *)(lVar7 + uVar11);
      if (bVar1 != 0) {
        if (bVar4) {
          uVar2 = bVar1 - 1;
          if (uVar2 <= uVar6 - uVar9) {
            memset((void *)(lVar8 + uVar10),0,(ulong)uVar2);
            bVar4 = false;
            uVar9 = uVar2 + uVar9;
            goto LAB_00100fc4;
          }
        }
        else if (uVar9 < uVar6) goto LAB_00100fb8;
LAB_00100fe4:
        bVar4 = false;
        goto LAB_00100fec;
      }
      if (uVar6 <= uVar9) goto LAB_00100fe4;
      bVar4 = true;
LAB_00100fb8:
      uVar9 = uVar9 + 1;
      *(byte *)(lVar8 + uVar10) = bVar1;
LAB_00100fc4:
      uVar11 = uVar11 + 1;
    } while (uVar11 < uVar5);
    bVar4 = true;
  }
  else {
    bVar4 = true;
  }
LAB_00100fec:
  (**(code **)(*param_1 + 0x600))(param_1,param_6,lVar7,2);
  (**(code **)(*param_1 + 0x600))(param_1,param_3,lVar8,0);
  iVar3 = uVar9 - param_4;
  if (!bVar4) {
    iVar3 = -1;
  }
  return iVar3;
}



// === __cxa_finalize @ 00113000 ===

/* WARNING: Control flow encountered bad instruction data */

void __cxa_finalize(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// === malloc @ 00113008 ===

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * malloc(size_t __size)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// === memcpy @ 00113010 ===

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * memcpy(void *__dest,void *__src,size_t __n)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// === memset @ 00113018 ===

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * memset(void *__s,int __c,size_t __n)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// === free @ 00113020 ===

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void free(void *__ptr)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// === __cxa_atexit @ 00113028 ===

/* WARNING: Control flow encountered bad instruction data */

void __cxa_atexit(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



