// View binding for ManageGridsActivity, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.grids;

import android.view.View;
import android.widget.ListView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;

public class ManageGridsActivity_ViewBinding implements Unbinder {
  private ManageGridsActivity target;

  private View view7f1001dc;

  @UiThread
  public ManageGridsActivity_ViewBinding(ManageGridsActivity target) {
    this(target, target.getWindow().getDecorView());
  }

  @UiThread
  public ManageGridsActivity_ViewBinding(final ManageGridsActivity target, View source) {
    this.target = target;

    View view;
    target.gridListView = Utils.findRequiredViewAsType(source, R.id.gridList, "field 'gridListView'", ListView.class);
    view = Utils.findRequiredView(source, R.id.add_new_grid_button, "method 'onAddNewGridButton'");
    view7f1001dc = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onAddNewGridButton();
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    ManageGridsActivity target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.gridListView = null;

    view7f1001dc.setOnClickListener(null);
    view7f1001dc = null;
  }
}
