// View binding for ParcelPropertiesFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.chat.profiles;

import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import androidx.cardview.widget.CardView;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;
import com.lumiyaviewer.lumiya.ui.chat.ChatterPicView;
import com.lumiyaviewer.lumiya.ui.common.ImageAssetView;

public class ParcelPropertiesFragment_ViewBinding implements Unbinder {
  private ParcelPropertiesFragment target;

  private View view7f10025e;

  private View view7f10025f;

  private View view7f100258;

  private View view7f10025b;

  private View view7f100261;

  @UiThread
  public ParcelPropertiesFragment_ViewBinding(final ParcelPropertiesFragment target, View source) {
    this.target = target;

    View view;
    view = Utils.findRequiredView(source, R.id.parcel_media_play_button, "field 'mediaPlayButton' and method 'onParcelMediaPlay'");
    target.mediaPlayButton = Utils.castView(view, R.id.parcel_media_play_button, "field 'mediaPlayButton'", Button.class);
    view7f10025e = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onParcelMediaPlay();
      }
    });
    view = Utils.findRequiredView(source, R.id.parcel_media_stop_button, "field 'mediaStopButton' and method 'onParcelMediaStop'");
    target.mediaStopButton = Utils.castView(view, R.id.parcel_media_stop_button, "field 'mediaStopButton'", Button.class);
    view7f10025f = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onParcelMediaStop();
      }
    });
    target.parcelArea = Utils.findRequiredViewAsType(source, R.id.parcel_area, "field 'parcelArea'", TextView.class);
    target.parcelDescription = Utils.findRequiredViewAsType(source, R.id.parcel_details_desc, "field 'parcelDescription'", TextView.class);
    target.parcelImageView = Utils.findRequiredViewAsType(source, R.id.parcel_image_view, "field 'parcelImageView'", ImageAssetView.class);
    target.parcelMediaCardView = Utils.findRequiredViewAsType(source, R.id.parcel_media_card_view, "field 'parcelMediaCardView'", CardView.class);
    target.parcelMediaURL = Utils.findRequiredViewAsType(source, R.id.parcel_media_url, "field 'parcelMediaURL'", TextView.class);
    target.parcelName = Utils.findRequiredViewAsType(source, R.id.parcel_name, "field 'parcelName'", TextView.class);
    target.parcelOwnerName = Utils.findRequiredViewAsType(source, R.id.parcel_owner_name, "field 'parcelOwnerName'", TextView.class);
    target.parcelOwnerPic = Utils.findRequiredViewAsType(source, R.id.parcel_owner_pic, "field 'parcelOwnerPic'", ChatterPicView.class);
    target.simRestartCardView = Utils.findRequiredViewAsType(source, R.id.sim_restart_card_view, "field 'simRestartCardView'", CardView.class);
    view = Utils.findRequiredView(source, R.id.parcel_owner_profile_button, "method 'onOwnerProfileButton'");
    view7f100258 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onOwnerProfileButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.parcel_set_home_button, "method 'onSetHomeButton'");
    view7f10025b = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onSetHomeButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.sim_restart_button, "method 'onSimRestartButton'");
    view7f100261 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onSimRestartButton();
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    ParcelPropertiesFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.mediaPlayButton = null;
    target.mediaStopButton = null;
    target.parcelArea = null;
    target.parcelDescription = null;
    target.parcelImageView = null;
    target.parcelMediaCardView = null;
    target.parcelMediaURL = null;
    target.parcelName = null;
    target.parcelOwnerName = null;
    target.parcelOwnerPic = null;
    target.simRestartCardView = null;

    view7f10025e.setOnClickListener(null);
    view7f10025e = null;
    view7f10025f.setOnClickListener(null);
    view7f10025f = null;
    view7f100258.setOnClickListener(null);
    view7f100258 = null;
    view7f10025b.setOnClickListener(null);
    view7f10025b = null;
    view7f100261.setOnClickListener(null);
    view7f100261 = null;
  }
}
