// View binding for UserPickFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.chat.profiles;

import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;
import com.lumiyaviewer.lumiya.ui.common.ImageAssetView;

public class UserPickFragment_ViewBinding implements Unbinder {
  private UserPickFragment target;

  private View view7f1002b2;

  private View view7f1002b0;

  private View view7f1002b4;

  private View view7f1002b1;

  @UiThread
  public UserPickFragment_ViewBinding(final UserPickFragment target, View source) {
    this.target = target;

    View view;
    view = Utils.findRequiredView(source, R.id.change_pic_button, "field 'changePicButton' and method 'onChangePic'");
    target.changePicButton = Utils.castView(view, R.id.change_pic_button, "field 'changePicButton'", Button.class);
    view7f1002b2 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onChangePic(p0);
      }
    });
    target.pickDescription = Utils.findRequiredViewAsType(source, R.id.pick_description, "field 'pickDescription'", TextView.class);
    view = Utils.findRequiredView(source, R.id.user_pick_set_location_button, "field 'setLocationButton' and method 'onSetLocation'");
    target.setLocationButton = Utils.castView(view, R.id.user_pick_set_location_button, "field 'setLocationButton'", Button.class);
    view7f1002b0 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onSetLocation(p0);
      }
    });
    view = Utils.findRequiredView(source, R.id.user_pick_desc_edit_button, "field 'userPickDescEditButton' and method 'onDescEdit'");
    target.userPickDescEditButton = Utils.castView(view, R.id.user_pick_desc_edit_button, "field 'userPickDescEditButton'", Button.class);
    view7f1002b4 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onDescEdit(p0);
      }
    });
    target.userPickImageView = Utils.findRequiredViewAsType(source, R.id.user_pick_image_view, "field 'userPickImageView'", ImageAssetView.class);
    view = Utils.findRequiredView(source, R.id.user_pick_teleport_button, "method 'onTeleportToPickClick'");
    view7f1002b1 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onTeleportToPickClick(p0);
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    UserPickFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.changePicButton = null;
    target.pickDescription = null;
    target.setLocationButton = null;
    target.userPickDescEditButton = null;
    target.userPickImageView = null;

    view7f1002b2.setOnClickListener(null);
    view7f1002b2 = null;
    view7f1002b0.setOnClickListener(null);
    view7f1002b0 = null;
    view7f1002b4.setOnClickListener(null);
    view7f1002b4 = null;
    view7f1002b1.setOnClickListener(null);
    view7f1002b1 = null;
  }
}
