// View binding for UserMainProfileTab, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.chat.profiles;

import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;
import com.lumiyaviewer.lumiya.ui.chat.ChatterPicView;
import com.lumiyaviewer.lumiya.ui.common.ImageAssetView;
import com.lumiyaviewer.lumiya.ui.common.LoadingLayout;

public class UserMainProfileTab_ViewBinding implements Unbinder {
  private UserMainProfileTab target;

  private View view7f1002ba;

  private View view7f1002b2;

  private View view7f1002c8;

  private View view7f1002cc;

  private View view7f1002c3;

  @UiThread
  public UserMainProfileTab_ViewBinding(final UserMainProfileTab target, View source) {
    this.target = target;

    View view;
    view = Utils.findRequiredView(source, R.id.about_edit_button, "field 'aboutEditButton' and method 'onAboutEditClicked'");
    target.aboutEditButton = Utils.castView(view, R.id.about_edit_button, "field 'aboutEditButton'", Button.class);
    view7f1002ba = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onAboutEditClicked(p0);
      }
    });
    view = Utils.findRequiredView(source, R.id.change_pic_button, "field 'changePicButton' and method 'onChangePicClicked'");
    target.changePicButton = Utils.castView(view, R.id.change_pic_button, "field 'changePicButton'", Button.class);
    view7f1002b2 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onChangePicClicked(p0);
      }
    });
    target.loadingLayout = Utils.findRequiredViewAsType(source, R.id.loading_layout, "field 'loadingLayout'", LoadingLayout.class);
    target.swipeRefreshLayout = Utils.findRequiredViewAsType(source, R.id.swipe_refresh_layout, "field 'swipeRefreshLayout'", SwipeRefreshLayout.class);
    target.textProfileAge = Utils.findRequiredViewAsType(source, R.id.text_profile_age, "field 'textProfileAge'", TextView.class);
    target.textProfileAgentKey = Utils.findRequiredViewAsType(source, R.id.text_profile_agent_key, "field 'textProfileAgentKey'", TextView.class);
    target.textProfileNotesText = Utils.findRequiredViewAsType(source, R.id.text_profile_notes_text, "field 'textProfileNotesText'", TextView.class);
    target.textProfileOnline = Utils.findRequiredViewAsType(source, R.id.text_profile_online, "field 'textProfileOnline'", TextView.class);
    target.textProfilePrimaryName = Utils.findRequiredViewAsType(source, R.id.text_profile_primary_name, "field 'textProfilePrimaryName'", TextView.class);
    target.textProfileSecondaryName = Utils.findRequiredViewAsType(source, R.id.text_profile_secondary_name, "field 'textProfileSecondaryName'", TextView.class);
    target.userPartnerCardView = Utils.findRequiredView(source, R.id.user_partner_card_view, "field 'userPartnerCardView'");
    target.userPicView = Utils.findRequiredViewAsType(source, R.id.user_pic_view, "field 'userPicView'", ImageAssetView.class);
    target.userProfileAboutText = Utils.findRequiredViewAsType(source, R.id.user_profile_about_text, "field 'userProfileAboutText'", TextView.class);
    target.userProfileNotesCaption = Utils.findRequiredView(source, R.id.user_profile_notes_caption, "field 'userProfileNotesCaption'");
    target.userProfilePartnerName = Utils.findRequiredViewAsType(source, R.id.user_profile_partner_name, "field 'userProfilePartnerName'", TextView.class);
    target.userProfilePartnerPic = Utils.findRequiredViewAsType(source, R.id.user_profile_partner_pic, "field 'userProfilePartnerPic'", ChatterPicView.class);
    target.userWebProfileCardView = Utils.findRequiredView(source, R.id.user_web_profile_card_view, "field 'userWebProfileCardView'");
    target.userWebProfileLink = Utils.findRequiredViewAsType(source, R.id.user_web_profile_link, "field 'userWebProfileLink'", TextView.class);
    view = Utils.findRequiredView(source, R.id.button_copy_agent_key, "method 'onCopyAgentKeyClicked'");
    view7f1002c8 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onCopyAgentKeyClicked(p0);
      }
    });
    view = Utils.findRequiredView(source, R.id.button_edit_notes, "method 'onEditNotesClicked'");
    view7f1002cc = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onEditNotesClicked(p0);
      }
    });
    view = Utils.findRequiredView(source, R.id.user_profile_view_partner_button, "method 'onViewProfileClicked'");
    view7f1002c3 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onViewProfileClicked(p0);
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    UserMainProfileTab target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.aboutEditButton = null;
    target.changePicButton = null;
    target.loadingLayout = null;
    target.swipeRefreshLayout = null;
    target.textProfileAge = null;
    target.textProfileAgentKey = null;
    target.textProfileNotesText = null;
    target.textProfileOnline = null;
    target.textProfilePrimaryName = null;
    target.textProfileSecondaryName = null;
    target.userPartnerCardView = null;
    target.userPicView = null;
    target.userProfileAboutText = null;
    target.userProfileNotesCaption = null;
    target.userProfilePartnerName = null;
    target.userProfilePartnerPic = null;
    target.userWebProfileCardView = null;
    target.userWebProfileLink = null;

    view7f1002ba.setOnClickListener(null);
    view7f1002ba = null;
    view7f1002b2.setOnClickListener(null);
    view7f1002b2 = null;
    view7f1002c8.setOnClickListener(null);
    view7f1002c8 = null;
    view7f1002cc.setOnClickListener(null);
    view7f1002cc = null;
    view7f1002c3.setOnClickListener(null);
    view7f1002c3 = null;
  }
}
