// View binding for UserFirstLifeProfileTab, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.chat.profiles;

import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;
import com.lumiyaviewer.lumiya.ui.common.ImageAssetView;
import com.lumiyaviewer.lumiya.ui.common.LoadingLayout;

public class UserFirstLifeProfileTab_ViewBinding implements Unbinder {
  private UserFirstLifeProfileTab target;

  private View view7f1002ba;

  private View view7f1002b2;

  @UiThread
  public UserFirstLifeProfileTab_ViewBinding(final UserFirstLifeProfileTab target, View source) {
    this.target = target;

    View view;
    view = Utils.findRequiredView(source, R.id.about_edit_button, "field 'aboutEditButton' and method 'onAboutEditClicked'");
    target.aboutEditButton = Utils.castView(view, R.id.about_edit_button, "field 'aboutEditButton'", Button.class);
    view7f1002ba = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onAboutEditClicked(p0);
      }
    });
    view = Utils.findRequiredView(source, R.id.change_pic_button, "field 'changePicButton' and method 'onChangePicClicked'");
    target.changePicButton = Utils.castView(view, R.id.change_pic_button, "field 'changePicButton'", Button.class);
    view7f1002b2 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onChangePicClicked(p0);
      }
    });
    target.loadingLayout = Utils.findRequiredViewAsType(source, R.id.loading_layout, "field 'loadingLayout'", LoadingLayout.class);
    target.swipeRefreshLayout = Utils.findRequiredViewAsType(source, R.id.swipe_refresh_layout, "field 'swipeRefreshLayout'", SwipeRefreshLayout.class);
    target.userPicView = Utils.findRequiredViewAsType(source, R.id.user_pic_view, "field 'userPicView'", ImageAssetView.class);
    target.userProfileAboutText = Utils.findRequiredViewAsType(source, R.id.user_profile_about_text, "field 'userProfileAboutText'", TextView.class);
    target.userProfilePaymentInfo = Utils.findRequiredViewAsType(source, R.id.text_profile_payment_info, "field 'userProfilePaymentInfo'", TextView.class);
  }

  @Override
  @CallSuper
  public void unbind() {
    UserFirstLifeProfileTab target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.aboutEditButton = null;
    target.changePicButton = null;
    target.loadingLayout = null;
    target.swipeRefreshLayout = null;
    target.userPicView = null;
    target.userProfileAboutText = null;
    target.userProfilePaymentInfo = null;

    view7f1002ba.setOnClickListener(null);
    view7f1002ba = null;
    view7f1002b2.setOnClickListener(null);
    view7f1002b2 = null;
  }
}
