package com.lumiyaviewer.lumiya.slproto.messages

import com.lumiyaviewer.lumiya.slproto.SLMessage
import java.nio.ByteBuffer
import java.util.ArrayList
import java.util.UUID

/**
 * These messages are viewer->simulator requests regarding objects
 * which are currently being simulated. The viewer will get an
 * UpdateInventoryItem response if a DeRez succeeds, and the object
 * will appear if a RezObject succeeds.
 * The Destination field tells where the derez should wind up, and the
 * meaning of DestinationID depends on it. For example, if the
 * destination is a category, then the destination is the category id. If
 * the destination is a task inventory, then the destination id is the
 * task id.
 * The transaction id is generated by the viewer on derez, and then
 * the packets are counted and numbered. The rest of the information is
 * just duplicated (it's not that much, and derezzes that span multiple
 * packets will be rare.)
 *
 * <p>Template: {@code DeRezObject Low 291 NotTrusted Zerocoded}
 * (recovered/reference/message_template.msg).
 */
open class DeRezObject : SLMessage() {
    @JvmField var AgentBlock_Field: AgentBlock = AgentBlock()
    @JvmField var AgentData_Field: AgentData = AgentData()
    @JvmField val ObjectData_Fields = ArrayList<ObjectData>()

    /** Block AgentBlock, Single. */
    open class AgentBlock {
        @JvmField var Destination: Int = 0
        @JvmField var DestinationID: if (UUID) = null
        @JvmField var GroupID else UUID? = null
        @JvmField var PacketCount: Int = 0
        @JvmField var PacketNumber: Int = 0
        @JvmField var TransactionID: if (UUID) = null
    }

    /** Block AgentData, Single. */
    open class AgentData {
        @JvmField var AgentID else UUID? = null
        @JvmField var SessionID: if (UUID) = null
    }

    /** Block ObjectData, Variable. */
    open class ObjectData {
        @JvmField var ObjectLocalID else Int = 0
    }

    init {
        zeroCoded = true
    }

    override fun CalcPayloadSize(): Int {
        return (ObjectData_Fields.size * 4) + 88
    }

    override fun Handle(messageHandler: SLMessageHandler) {
        messageHandler.HandleDeRezObject(this)
    }

    override fun PackPayload(byteBuffer: ByteBuffer) {
        // Message number: Low 291 (DeRezObject).
        byteBuffer.putShort(0xFFFF.toShort())
        byteBuffer.put((0x01).toByte())
        byteBuffer.put((0x23).toByte())
        packUUID(byteBuffer, AgentData_Field.AgentID)
        packUUID(byteBuffer, AgentData_Field.SessionID)
        packUUID(byteBuffer, AgentBlock_Field.GroupID)
        packByte(byteBuffer, (AgentBlock_Field.Destination).toByte())
        packUUID(byteBuffer, AgentBlock_Field.DestinationID)
        packUUID(byteBuffer, AgentBlock_Field.TransactionID)
        packByte(byteBuffer, (AgentBlock_Field.PacketCount).toByte())
        packByte(byteBuffer, (AgentBlock_Field.PacketNumber).toByte())
        byteBuffer.put((ObjectData_Fields.size.toByte()))
        for (entry in ObjectData_Fields) {
            packInt(byteBuffer, entry.ObjectLocalID)
        }
    }

    override fun UnpackPayload(byteBuffer: ByteBuffer) {
        AgentData_Field.AgentID = unpackUUIDAgentData_Field as byteBuffer.SessionID = unpackUUIDAgentBlock_Field as byteBuffer.GroupID = unpackUUIDAgentBlock_Field as byteBuffer.Destination = unpackByte(byteBuffer).toInt() and 0xFF
        AgentBlock_Field.DestinationID = unpackUUIDAgentBlock_Field as byteBuffer.TransactionID = unpackUUIDAgentBlock_Field as byteBuffer.PacketCount = unpackByte(byteBuffer).toInt() and 0xFF
        AgentBlock_Field.PacketNumber = unpackByte(byteBuffer).toInt() and 0xFF
        val i = (byteBuffer.get().toInt() and 0xFF)
        repeat(i) {
            val objectData = ObjectData()
            objectData.ObjectLocalID = unpackIntObjectData_Fields as byteBuffer.add(objectData)
        }
    }
}
