package com.lumiyaviewer.lumiya.slproto.messages;

import com.lumiyaviewer.lumiya.slproto.SLMessage;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.UUID;

/**
 * These messages are viewer->simulator requests regarding objects
 * which are currently being simulated. The viewer will get an
 * UpdateInventoryItem response if a DeRez succeeds, and the object
 * will appear if a RezObject succeeds.
 * The Destination field tells where the derez should wind up, and the
 * meaning of DestinationID depends on it. For example, if the
 * destination is a category, then the destination is the category id. If
 * the destination is a task inventory, then the destination id is the
 * task id.
 * The transaction id is generated by the viewer on derez, and then
 * the packets are counted and numbered. The rest of the information is
 * just duplicated (it's not that much, and derezzes that span multiple
 * packets will be rare.)
 *
 * <p>Template: {@code DeRezObject Low 291 NotTrusted Zerocoded}
 * (recovered/reference/message_template.msg).
 */
public class DeRezObject extends SLMessage {
    public AgentBlock AgentBlock_Field;
    public AgentData AgentData_Field;
    public ArrayList<ObjectData> ObjectData_Fields = new ArrayList<>();

    /** Block AgentBlock, Single. */
    public static class AgentBlock {
        public int Destination; // U8
        public UUID DestinationID; // LLUUID - see above
        public UUID GroupID; // LLUUID
        public int PacketCount; // U8
        public int PacketNumber; // U8
        public UUID TransactionID; // LLUUID
    }

    /** Block AgentData, Single. */
    public static class AgentData {
        public UUID AgentID; // LLUUID
        public UUID SessionID; // LLUUID
    }

    /** Block ObjectData, Variable. */
    public static class ObjectData {
        public int ObjectLocalID; // U32 - object id in world
    }

    public DeRezObject() {
        this.zeroCoded = true;
        this.AgentData_Field = new AgentData();
        this.AgentBlock_Field = new AgentBlock();
    }

    @Override
    public int CalcPayloadSize() {
        return (this.ObjectData_Fields.size() * 4) + 88;
    }

    @Override
    public void Handle(SLMessageHandler messageHandler) {
        messageHandler.HandleDeRezObject(this);
    }

    @Override
    public void PackPayload(ByteBuffer byteBuffer) {
        // Message number: Low 291 (DeRezObject).
        byteBuffer.putShort((short) 0xFFFF);
        byteBuffer.put((byte) 0x01);
        byteBuffer.put((byte) 0x23);
        packUUID(byteBuffer, this.AgentData_Field.AgentID);
        packUUID(byteBuffer, this.AgentData_Field.SessionID);
        packUUID(byteBuffer, this.AgentBlock_Field.GroupID);
        packByte(byteBuffer, (byte) this.AgentBlock_Field.Destination);
        packUUID(byteBuffer, this.AgentBlock_Field.DestinationID);
        packUUID(byteBuffer, this.AgentBlock_Field.TransactionID);
        packByte(byteBuffer, (byte) this.AgentBlock_Field.PacketCount);
        packByte(byteBuffer, (byte) this.AgentBlock_Field.PacketNumber);
        byteBuffer.put((byte) this.ObjectData_Fields.size());
        Iterator<?> it = this.ObjectData_Fields.iterator();
        while (it.hasNext()) {
            packInt(byteBuffer, ((ObjectData) it.next()).ObjectLocalID);
        }
    }

    @Override
    public void UnpackPayload(ByteBuffer byteBuffer) {
        this.AgentData_Field.AgentID = unpackUUID(byteBuffer);
        this.AgentData_Field.SessionID = unpackUUID(byteBuffer);
        this.AgentBlock_Field.GroupID = unpackUUID(byteBuffer);
        this.AgentBlock_Field.Destination = unpackByte(byteBuffer) & 0xFF;
        this.AgentBlock_Field.DestinationID = unpackUUID(byteBuffer);
        this.AgentBlock_Field.TransactionID = unpackUUID(byteBuffer);
        this.AgentBlock_Field.PacketCount = unpackByte(byteBuffer) & 0xFF;
        this.AgentBlock_Field.PacketNumber = unpackByte(byteBuffer) & 0xFF;
        int i = byteBuffer.get() & 0xFF;
        for (int j = 0; j < i; j++) {
            ObjectData objectData = new ObjectData();
            objectData.ObjectLocalID = unpackInt(byteBuffer);
            this.ObjectData_Fields.add(objectData);
        }
    }
}
