// View binding for CardboardActivity, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.render;

import android.annotation.SuppressLint;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;
import com.lumiyaviewer.lumiya.ui.voice.VoiceStatusView;

public class CardboardActivity_ViewBinding implements Unbinder {
  private CardboardActivity target;

  private View view7f1000f9;

  private View view7f1000fe;

  private View view7f1000fc;

  private View view7f100106;

  private View view7f100105;

  private View view7f1000f8;

  private View view7f100111;

  private View view7f100100;

  private View view7f1000f7;

  private View view7f100104;

  private View view7f1000fd;

  private View view7f1000ff;

  private View view7f100101;

  private View view7f100102;

  private View view7f100112;

  private View view7f10010d;

  private View view7f10010b;

  private View view7f10010a;

  private View view7f100108;

  @UiThread
  public CardboardActivity_ViewBinding(CardboardActivity target) {
    this(target, target.getWindow().getDecorView());
  }

  @UiThread
  @SuppressLint("ClickableViewAccessibility")
  public CardboardActivity_ViewBinding(final CardboardActivity target, View source) {
    this.target = target;

    View view;
    view = Utils.findRequiredView(source, R.id.button_chat, "field 'buttonChat' and method 'onChatButton'");
    target.buttonChat = Utils.castView(view, R.id.button_chat, "field 'buttonChat'", ImageButton.class);
    view7f1000f9 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onChatButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.button_move_backward, "field 'buttonMoveBackward' and method 'onCamButtonTouch'");
    target.buttonMoveBackward = Utils.castView(view, R.id.button_move_backward, "field 'buttonMoveBackward'", ImageButton.class);
    view7f1000fe = view;
    view.setOnTouchListener(new View.OnTouchListener() {
      @Override
      public boolean onTouch(View p0, MotionEvent p1) {
        return target.onCamButtonTouch(p0, p1);
      }
    });
    view = Utils.findRequiredView(source, R.id.button_move_forward, "field 'buttonMoveForward' and method 'onCamButtonTouch'");
    target.buttonMoveForward = Utils.castView(view, R.id.button_move_forward, "field 'buttonMoveForward'", ImageButton.class);
    view7f1000fc = view;
    view.setOnTouchListener(new View.OnTouchListener() {
      @Override
      public boolean onTouch(View p0, MotionEvent p1) {
        return target.onCamButtonTouch(p0, p1);
      }
    });
    view = Utils.findRequiredView(source, R.id.object_chat_button, "field 'buttonObjectChat' and method 'onObjectChat'");
    target.buttonObjectChat = Utils.castView(view, R.id.object_chat_button, "field 'buttonObjectChat'", ImageButton.class);
    view7f100106 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectChat();
      }
    });
    view = Utils.findRequiredView(source, R.id.object_sit_button, "field 'buttonSit' and method 'onObjectSit'");
    target.buttonSit = Utils.castView(view, R.id.object_sit_button, "field 'buttonSit'", ImageButton.class);
    view7f100105 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectSit();
      }
    });
    view = Utils.findRequiredView(source, R.id.button_speak, "field 'buttonSpeak' and method 'onSpeakButton'");
    target.buttonSpeak = Utils.castView(view, R.id.button_speak, "field 'buttonSpeak'", ImageButton.class);
    view7f1000f8 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onSpeakButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.button_speech_send, "field 'buttonSpeechSend' and method 'onSpeechSendButton'");
    target.buttonSpeechSend = Utils.castView(view, R.id.button_speech_send, "field 'buttonSpeechSend'", ImageButton.class);
    view7f100111 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onSpeechSendButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.button_stand_up, "field 'buttonStandUp' and method 'onStandUpButton'");
    target.buttonStandUp = Utils.castView(view, R.id.button_stand_up, "field 'buttonStandUp'", ImageButton.class);
    view7f100100 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onStandUpButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.button_touch, "field 'buttonTouch' and method 'onTouchButton'");
    target.buttonTouch = Utils.castView(view, R.id.button_touch, "field 'buttonTouch'", ImageButton.class);
    view7f1000f7 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onTouchButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.object_touch_button, "field 'buttonTouchObject' and method 'onObjectTouch'");
    target.buttonTouchObject = Utils.castView(view, R.id.object_touch_button, "field 'buttonTouchObject'", ImageButton.class);
    view7f100104 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectTouch();
      }
    });
    view = Utils.findRequiredView(source, R.id.button_turn_left, "field 'buttonTurnLeft' and method 'onCamButtonTouch'");
    target.buttonTurnLeft = Utils.castView(view, R.id.button_turn_left, "field 'buttonTurnLeft'", ImageButton.class);
    view7f1000fd = view;
    view.setOnTouchListener(new View.OnTouchListener() {
      @Override
      public boolean onTouch(View p0, MotionEvent p1) {
        return target.onCamButtonTouch(p0, p1);
      }
    });
    view = Utils.findRequiredView(source, R.id.button_turn_right, "field 'buttonTurnRight' and method 'onCamButtonTouch'");
    target.buttonTurnRight = Utils.castView(view, R.id.button_turn_right, "field 'buttonTurnRight'", ImageButton.class);
    view7f1000ff = view;
    view.setOnTouchListener(new View.OnTouchListener() {
      @Override
      public boolean onTouch(View p0, MotionEvent p1) {
        return target.onCamButtonTouch(p0, p1);
      }
    });
    view = Utils.findRequiredView(source, R.id.cardboard_aim_controls, "field 'cardboardAimControls' and method 'onAimControlsTouch'");
    target.cardboardAimControls = Utils.castView(view, R.id.cardboard_aim_controls, "field 'cardboardAimControls'", ViewGroup.class);
    view7f100101 = view;
    view.setOnTouchListener(new View.OnTouchListener() {
      @Override
      public boolean onTouch(View p0, MotionEvent p1) {
        return target.onAimControlsTouch(p0, p1);
      }
    });
    target.cardboardDetailsPage = Utils.findRequiredViewAsType(source, R.id.cardboard_details_page, "field 'cardboardDetailsPage'", ViewGroup.class);
    view = Utils.findRequiredView(source, R.id.cardboard_object_controls, "field 'cardboardObjectControls' and method 'onObjectControlsTouch'");
    target.cardboardObjectControls = Utils.castView(view, R.id.cardboard_object_controls, "field 'cardboardObjectControls'", ViewGroup.class);
    view7f100102 = view;
    view.setOnTouchListener(new View.OnTouchListener() {
      @Override
      public boolean onTouch(View p0, MotionEvent p1) {
        return target.onObjectControlsTouch(p0, p1);
      }
    });
    target.cardboardPrimaryControls = Utils.findRequiredViewAsType(source, R.id.cardboard_primary_controls, "field 'cardboardPrimaryControls'", ViewGroup.class);
    view = Utils.findRequiredView(source, R.id.cardboard_script_dialog, "field 'cardboardScriptDialog' and method 'onScriptDialogOutsideTouch'");
    target.cardboardScriptDialog = Utils.castView(view, R.id.cardboard_script_dialog, "field 'cardboardScriptDialog'", ViewGroup.class);
    view7f100112 = view;
    view.setOnTouchListener(new View.OnTouchListener() {
      @Override
      public boolean onTouch(View p0, MotionEvent p1) {
        return target.onScriptDialogOutsideTouch(p0, p1);
      }
    });
    view = Utils.findRequiredView(source, R.id.cardboard_speak_controls, "field 'cardboardSpeakControls' and method 'onSpeakControlsTouch'");
    target.cardboardSpeakControls = Utils.castView(view, R.id.cardboard_speak_controls, "field 'cardboardSpeakControls'", ViewGroup.class);
    view7f10010d = view;
    view.setOnTouchListener(new View.OnTouchListener() {
      @Override
      public boolean onTouch(View p0, MotionEvent p1) {
        return target.onSpeakControlsTouch(p0, p1);
      }
    });
    target.chatsOverlayLayout = Utils.findRequiredViewAsType(source, R.id.cardboard_ims, "field 'chatsOverlayLayout'", LinearLayout.class);
    target.dialogQuestionText = Utils.findRequiredViewAsType(source, R.id.dialogQuestionText, "field 'dialogQuestionText'", TextView.class);
    target.moveButtonsLayout = Utils.findRequiredViewAsType(source, R.id.move_buttons_layout, "field 'moveButtonsLayout'", ViewGroup.class);
    view = Utils.findRequiredView(source, R.id.cardboard_no_button, "field 'noButton' and method 'onNoButton'");
    target.noButton = Utils.castView(view, R.id.cardboard_no_button, "field 'noButton'", ImageButton.class);
    view7f10010b = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onNoButton();
      }
    });
    target.objectNameView = Utils.findRequiredViewAsType(source, R.id.cardboard_object_name, "field 'objectNameView'", TextView.class);
    target.speakLevelIndicator = Utils.findRequiredViewAsType(source, R.id.speak_level_indicator, "field 'speakLevelIndicator'", ProgressBar.class);
    target.speakNowText = Utils.findRequiredViewAsType(source, R.id.speak_now_text, "field 'speakNowText'", TextView.class);
    target.speechRecognitionResults = Utils.findRequiredViewAsType(source, R.id.speech_recognition_results, "field 'speechRecognitionResults'", TextView.class);
    target.voiceStatusView = Utils.findRequiredViewAsType(source, R.id.cardboard_voice_status_view, "field 'voiceStatusView'", VoiceStatusView.class);
    view = Utils.findRequiredView(source, R.id.cardboard_yes_button, "field 'yesButton' and method 'onYesButton'");
    target.yesButton = Utils.castView(view, R.id.cardboard_yes_button, "field 'yesButton'", ImageButton.class);
    view7f10010a = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onYesButton();
      }
    });
    target.yesNoText = Utils.findRequiredViewAsType(source, R.id.cardboard_yesno_text, "field 'yesNoText'", TextView.class);
    view = Utils.findRequiredView(source, R.id.cardboard_yesno_dialog, "method 'onYesNoOutsideTouch'");
    view7f100108 = view;
    view.setOnTouchListener(new View.OnTouchListener() {
      @Override
      public boolean onTouch(View p0, MotionEvent p1) {
        return target.onYesNoOutsideTouch(p0, p1);
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    CardboardActivity target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.buttonChat = null;
    target.buttonMoveBackward = null;
    target.buttonMoveForward = null;
    target.buttonObjectChat = null;
    target.buttonSit = null;
    target.buttonSpeak = null;
    target.buttonSpeechSend = null;
    target.buttonStandUp = null;
    target.buttonTouch = null;
    target.buttonTouchObject = null;
    target.buttonTurnLeft = null;
    target.buttonTurnRight = null;
    target.cardboardAimControls = null;
    target.cardboardDetailsPage = null;
    target.cardboardObjectControls = null;
    target.cardboardPrimaryControls = null;
    target.cardboardScriptDialog = null;
    target.cardboardSpeakControls = null;
    target.chatsOverlayLayout = null;
    target.dialogQuestionText = null;
    target.moveButtonsLayout = null;
    target.noButton = null;
    target.objectNameView = null;
    target.speakLevelIndicator = null;
    target.speakNowText = null;
    target.speechRecognitionResults = null;
    target.voiceStatusView = null;
    target.yesButton = null;
    target.yesNoText = null;

    view7f1000f9.setOnClickListener(null);
    view7f1000f9 = null;
    view7f1000fe.setOnTouchListener(null);
    view7f1000fe = null;
    view7f1000fc.setOnTouchListener(null);
    view7f1000fc = null;
    view7f100106.setOnClickListener(null);
    view7f100106 = null;
    view7f100105.setOnClickListener(null);
    view7f100105 = null;
    view7f1000f8.setOnClickListener(null);
    view7f1000f8 = null;
    view7f100111.setOnClickListener(null);
    view7f100111 = null;
    view7f100100.setOnClickListener(null);
    view7f100100 = null;
    view7f1000f7.setOnClickListener(null);
    view7f1000f7 = null;
    view7f100104.setOnClickListener(null);
    view7f100104 = null;
    view7f1000fd.setOnTouchListener(null);
    view7f1000fd = null;
    view7f1000ff.setOnTouchListener(null);
    view7f1000ff = null;
    view7f100101.setOnTouchListener(null);
    view7f100101 = null;
    view7f100102.setOnTouchListener(null);
    view7f100102 = null;
    view7f100112.setOnTouchListener(null);
    view7f100112 = null;
    view7f10010d.setOnTouchListener(null);
    view7f10010d = null;
    view7f10010b.setOnClickListener(null);
    view7f10010b = null;
    view7f10010a.setOnClickListener(null);
    view7f10010a = null;
    view7f100108.setOnTouchListener(null);
    view7f100108 = null;
  }
}
