// View binding for WorldViewActivity, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.render;

import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;
import com.lumiyaviewer.lumiya.ui.voice.VoiceStatusView;

public class WorldViewActivity_ViewBinding implements Unbinder {
  private WorldViewActivity target;

  private View view7f1002f2;

  private View view7f1002f1;

  private View view7f1002f3;

  private View view7f100100;

  private View view7f1002ee;

  private View view7f100106;

  private View view7f1002ea;

  private View view7f100222;

  private View view7f100105;

  private View view7f100212;

  private View view7f100104;

  @UiThread
  public WorldViewActivity_ViewBinding(WorldViewActivity target) {
    this(target, target.getWindow().getDecorView());
  }

  @UiThread
  public WorldViewActivity_ViewBinding(final WorldViewActivity target, View source) {
    this.target = target;

    View view;
    target.avatarIconView = Utils.findRequiredViewAsType(source, R.id.avatarIconView, "field 'avatarIconView'", ImageView.class);
    view = Utils.findRequiredView(source, R.id.button_cam_off, "field 'buttonCamOff' and method 'onCamOffButton'");
    target.buttonCamOff = Utils.castView(view, R.id.button_cam_off, "field 'buttonCamOff'", ImageButton.class);
    view7f1002f2 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onCamOffButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.button_cam_on, "field 'buttonCamOn' and method 'onCamOnButton'");
    target.buttonCamOn = Utils.castView(view, R.id.button_cam_on, "field 'buttonCamOn'", ImageButton.class);
    view7f1002f1 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onCamOnButton();
      }
    });
    target.buttonFlyDownward = Utils.findRequiredViewAsType(source, R.id.button_fly_downward, "field 'buttonFlyDownward'", ImageButton.class);
    target.buttonFlyUpward = Utils.findRequiredViewAsType(source, R.id.button_fly_upward, "field 'buttonFlyUpward'", ImageButton.class);
    view = Utils.findRequiredView(source, R.id.button_hud, "field 'buttonHUD' and method 'onHUDButton'");
    target.buttonHUD = Utils.castView(view, R.id.button_hud, "field 'buttonHUD'", Button.class);
    view7f1002f3 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onHUDButton();
      }
    });
    target.buttonMoveBackward = Utils.findRequiredViewAsType(source, R.id.button_move_backward, "field 'buttonMoveBackward'", ImageButton.class);
    target.buttonMoveForward = Utils.findRequiredViewAsType(source, R.id.button_move_forward, "field 'buttonMoveForward'", ImageButton.class);
    view = Utils.findRequiredView(source, R.id.button_stand_up, "field 'buttonStandUp' and method 'onObjectStandButton'");
    target.buttonStandUp = Utils.castView(view, R.id.button_stand_up, "field 'buttonStandUp'", ImageButton.class);
    view7f100100 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectStandButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.button_stop_flying, "field 'buttonStopFlying' and method 'onStopFlyingButton'");
    target.buttonStopFlying = Utils.castView(view, R.id.button_stop_flying, "field 'buttonStopFlying'", ImageButton.class);
    view7f1002ee = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onStopFlyingButton();
      }
    });
    target.buttonTurnLeft = Utils.findRequiredViewAsType(source, R.id.button_turn_left, "field 'buttonTurnLeft'", ImageButton.class);
    target.buttonTurnRight = Utils.findRequiredViewAsType(source, R.id.button_turn_right, "field 'buttonTurnRight'", ImageButton.class);
    target.chatsOverlayLayout = Utils.findRequiredViewAsType(source, R.id.chats_overlay_layout, "field 'chatsOverlayLayout'", LinearLayout.class);
    target.detailsContainer = Utils.findRequiredView(source, R.id.details, "field 'detailsContainer'");
    target.dragPointer = Utils.findRequiredView(source, R.id.drag_pointer_view, "field 'dragPointer'");
    target.dragPointerLayout = Utils.findRequiredViewAsType(source, R.id.drag_pointer_layout, "field 'dragPointerLayout'", ViewGroup.class);
    target.flyButtonsLayout = Utils.findRequiredViewAsType(source, R.id.fly_buttons_layout, "field 'flyButtonsLayout'", LinearLayout.class);
    target.insetsBackground = Utils.findRequiredViewAsType(source, R.id.insets_background, "field 'insetsBackground'", FrameLayout.class);
    target.moveButtonsLayout = Utils.findRequiredView(source, R.id.move_buttons_layout, "field 'moveButtonsLayout'");
    view = Utils.findRequiredView(source, R.id.object_chat_button, "field 'objectChatButton' and method 'onObjectChatButton'");
    target.objectChatButton = Utils.castView(view, R.id.object_chat_button, "field 'objectChatButton'", ImageButton.class);
    view7f100106 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectChatButton();
      }
    });
    target.objectControlsPanel = Utils.findRequiredView(source, R.id.object_controls_panel, "field 'objectControlsPanel'");
    view = Utils.findRequiredView(source, R.id.object_more_button, "field 'objectMoreButton' and method 'onObjectMoreButton'");
    target.objectMoreButton = Utils.castView(view, R.id.object_more_button, "field 'objectMoreButton'", ImageButton.class);
    view7f1002ea = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectMoreButton();
      }
    });
    target.objectNameTextView = Utils.findRequiredViewAsType(source, R.id.objectNameTextView, "field 'objectNameTextView'", TextView.class);
    view = Utils.findRequiredView(source, R.id.object_pay_button, "field 'objectPayButton' and method 'onObjectPayButton'");
    target.objectPayButton = Utils.castView(view, R.id.object_pay_button, "field 'objectPayButton'", ImageButton.class);
    view7f100222 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectPayButton();
      }
    });
    target.objectPopupLeftSpacer = Utils.findRequiredView(source, R.id.object_popup_left_spacer, "field 'objectPopupLeftSpacer'");
    view = Utils.findRequiredView(source, R.id.object_sit_button, "field 'objectSitButton' and method 'onObjectSitButton'");
    target.objectSitButton = Utils.castView(view, R.id.object_sit_button, "field 'objectSitButton'", ImageButton.class);
    view7f100105 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectSitButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.object_stand_button, "field 'objectStandButton' and method 'onObjectStandButton'");
    target.objectStandButton = Utils.castView(view, R.id.object_stand_button, "field 'objectStandButton'", ImageButton.class);
    view7f100212 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectStandButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.object_touch_button, "field 'objectTouchButton' and method 'onObjectTouchButton'");
    target.objectTouchButton = Utils.castView(view, R.id.object_touch_button, "field 'objectTouchButton'", ImageButton.class);
    view7f100104 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onObjectTouchButton();
      }
    });
    target.voiceStatusView = Utils.findRequiredViewAsType(source, R.id.voice_status_view_3d, "field 'voiceStatusView'", VoiceStatusView.class);
    target.worldOverlaysContainer = Utils.findRequiredViewAsType(source, R.id.world_overlays_container, "field 'worldOverlaysContainer'", ViewGroup.class);
    target.worldViewHolder = Utils.findRequiredViewAsType(source, R.id.world_view_holder, "field 'worldViewHolder'", FrameLayout.class);
    target.worldViewTouchReceiver = Utils.findRequiredView(source, R.id.world_view_touch_receiver, "field 'worldViewTouchReceiver'");
  }

  @Override
  @CallSuper
  public void unbind() {
    WorldViewActivity target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.avatarIconView = null;
    target.buttonCamOff = null;
    target.buttonCamOn = null;
    target.buttonFlyDownward = null;
    target.buttonFlyUpward = null;
    target.buttonHUD = null;
    target.buttonMoveBackward = null;
    target.buttonMoveForward = null;
    target.buttonStandUp = null;
    target.buttonStopFlying = null;
    target.buttonTurnLeft = null;
    target.buttonTurnRight = null;
    target.chatsOverlayLayout = null;
    target.detailsContainer = null;
    target.dragPointer = null;
    target.dragPointerLayout = null;
    target.flyButtonsLayout = null;
    target.insetsBackground = null;
    target.moveButtonsLayout = null;
    target.objectChatButton = null;
    target.objectControlsPanel = null;
    target.objectMoreButton = null;
    target.objectNameTextView = null;
    target.objectPayButton = null;
    target.objectPopupLeftSpacer = null;
    target.objectSitButton = null;
    target.objectStandButton = null;
    target.objectTouchButton = null;
    target.voiceStatusView = null;
    target.worldOverlaysContainer = null;
    target.worldViewHolder = null;
    target.worldViewTouchReceiver = null;

    view7f1002f2.setOnClickListener(null);
    view7f1002f2 = null;
    view7f1002f1.setOnClickListener(null);
    view7f1002f1 = null;
    view7f1002f3.setOnClickListener(null);
    view7f1002f3 = null;
    view7f100100.setOnClickListener(null);
    view7f100100 = null;
    view7f1002ee.setOnClickListener(null);
    view7f1002ee = null;
    view7f100106.setOnClickListener(null);
    view7f100106 = null;
    view7f1002ea.setOnClickListener(null);
    view7f1002ea = null;
    view7f100222.setOnClickListener(null);
    view7f100222 = null;
    view7f100105.setOnClickListener(null);
    view7f100105 = null;
    view7f100212.setOnClickListener(null);
    view7f100212 = null;
    view7f100104.setOnClickListener(null);
    view7f100104 = null;
  }
}
