// View binding for VoiceStatusView, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.voice;

import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.SeekBar;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import androidx.cardview.widget.CardView;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;

public class VoiceStatusView_ViewBinding implements Unbinder {
  private VoiceStatusView target;

  private View view7f1002d3;

  private View view7f1002dc;

  private View view7f1002db;

  private View view7f1002d2;

  private View view7f1002d1;

  private View view7f1002d0;

  private View view7f1002d8;

  @UiThread
  public VoiceStatusView_ViewBinding(VoiceStatusView target) {
    this(target, target);
  }

  @UiThread
  public VoiceStatusView_ViewBinding(final VoiceStatusView target, View source) {
    this.target = target;

    View view;
    view = Utils.findRequiredView(source, R.id.voice_answer_button, "field 'voiceAnswerButton' and method 'onVoiceAnswerButton'");
    target.voiceAnswerButton = Utils.castView(view, R.id.voice_answer_button, "field 'voiceAnswerButton'", ImageButton.class);
    view7f1002d3 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onVoiceAnswerButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.voice_bluetooth_button, "field 'voiceBluetoothButton' and method 'onVoiceBluetoothButton'");
    target.voiceBluetoothButton = Utils.castView(view, R.id.voice_bluetooth_button, "field 'voiceBluetoothButton'", Button.class);
    view7f1002dc = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onVoiceBluetoothButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.voice_loudspeaker_button, "field 'voiceLoudspeakerButton' and method 'onLoudspeakerButton'");
    target.voiceLoudspeakerButton = Utils.castView(view, R.id.voice_loudspeaker_button, "field 'voiceLoudspeakerButton'", Button.class);
    view7f1002db = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onLoudspeakerButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.voice_mic_off_button, "field 'voiceMicOffButton' and method 'onVoiceMicOffButton'");
    target.voiceMicOffButton = Utils.castView(view, R.id.voice_mic_off_button, "field 'voiceMicOffButton'", ImageButton.class);
    view7f1002d2 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onVoiceMicOffButton();
      }
    });
    view = Utils.findRequiredView(source, R.id.voice_mic_on_button, "field 'voiceMicOnButton' and method 'onVoiceMicOnButton'");
    target.voiceMicOnButton = Utils.castView(view, R.id.voice_mic_on_button, "field 'voiceMicOnButton'", ImageButton.class);
    view7f1002d1 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onVoiceMicOnButton();
      }
    });
    target.voiceSpeakIndicatorLeft = Utils.findRequiredViewAsType(source, R.id.voice_speak_indicator_left, "field 'voiceSpeakIndicatorLeft'", ImageView.class);
    target.voiceSpeakIndicatorRight = Utils.findRequiredViewAsType(source, R.id.voice_speak_indicator_right, "field 'voiceSpeakIndicatorRight'", ImageView.class);
    target.voiceSpeakerVolumeControl = Utils.findRequiredViewAsType(source, R.id.voice_speaker_volume_control, "field 'voiceSpeakerVolumeControl'", SeekBar.class);
    view = Utils.findRequiredView(source, R.id.voice_status_card_view, "field 'voiceStatusCardView' and method 'onVoiceStatusCardClick'");
    target.voiceStatusCardView = Utils.castView(view, R.id.voice_status_card_view, "field 'voiceStatusCardView'", CardView.class);
    view7f1002d0 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onVoiceStatusCardClick();
      }
    });
    target.voiceStatusControls = Utils.findRequiredViewAsType(source, R.id.voice_status_controls, "field 'voiceStatusControls'", ViewGroup.class);
    target.voiceStatusSmallText = Utils.findRequiredViewAsType(source, R.id.voice_status_small_text, "field 'voiceStatusSmallText'", TextView.class);
    target.voiceStatusText = Utils.findRequiredViewAsType(source, R.id.voice_status_text, "field 'voiceStatusText'", TextView.class);
    view = Utils.findRequiredView(source, R.id.voice_terminate_button, "field 'voiceTerminateButton' and method 'onVoiceTerminateButton'");
    target.voiceTerminateButton = Utils.castView(view, R.id.voice_terminate_button, "field 'voiceTerminateButton'", ImageButton.class);
    view7f1002d8 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onVoiceTerminateButton();
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    VoiceStatusView target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.voiceAnswerButton = null;
    target.voiceBluetoothButton = null;
    target.voiceLoudspeakerButton = null;
    target.voiceMicOffButton = null;
    target.voiceMicOnButton = null;
    target.voiceSpeakIndicatorLeft = null;
    target.voiceSpeakIndicatorRight = null;
    target.voiceSpeakerVolumeControl = null;
    target.voiceStatusCardView = null;
    target.voiceStatusControls = null;
    target.voiceStatusSmallText = null;
    target.voiceStatusText = null;
    target.voiceTerminateButton = null;

    view7f1002d3.setOnClickListener(null);
    view7f1002d3 = null;
    view7f1002dc.setOnClickListener(null);
    view7f1002dc = null;
    view7f1002db.setOnClickListener(null);
    view7f1002db = null;
    view7f1002d2.setOnClickListener(null);
    view7f1002d2 = null;
    view7f1002d1.setOnClickListener(null);
    view7f1002d1 = null;
    view7f1002d0.setOnClickListener(null);
    view7f1002d0 = null;
    view7f1002d8.setOnClickListener(null);
    view7f1002d8 = null;
  }
}
