// View binding for MinimapActivity, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.minimap;

import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;

public class MinimapActivity_ViewBinding implements Unbinder {
  private MinimapActivity target;

  @UiThread
  public MinimapActivity_ViewBinding(MinimapActivity target) {
    this(target, target.getWindow().getDecorView());
  }

  @UiThread
  public MinimapActivity_ViewBinding(MinimapActivity target, View source) {
    this.target = target;

    target.detailsLayout = Utils.findRequiredViewAsType(source, R.id.detailsWithOnlineStatus, "field 'detailsLayout'", ViewGroup.class);
    target.selectorLayout = Utils.findRequiredViewAsType(source, R.id.selector, "field 'selectorLayout'", FrameLayout.class);
    target.splitMainLayout = Utils.findRequiredViewAsType(source, R.id.splitMainLayout, "field 'splitMainLayout'", LinearLayout.class);
    target.splitObjectPopupsLeftSpacer = Utils.findRequiredView(source, R.id.split_object_popups_left_spacer, "field 'splitObjectPopupsLeftSpacer'");
  }

  @Override
  @CallSuper
  public void unbind() {
    MinimapActivity target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.detailsLayout = null;
    target.selectorLayout = null;
    target.splitMainLayout = null;
    target.splitObjectPopupsLeftSpacer = null;
  }
}
