// View binding for NearbyPeopleMinimapFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.minimap;

import android.view.View;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import androidx.recyclerview.widget.RecyclerView;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;

public class NearbyPeopleMinimapFragment_ViewBinding implements Unbinder {
  private NearbyPeopleMinimapFragment target;

  @UiThread
  public NearbyPeopleMinimapFragment_ViewBinding(NearbyPeopleMinimapFragment target, View source) {
    this.target = target;

    target.emptyView = Utils.findRequiredView(source, android.R.id.empty, "field 'emptyView'");
    target.userListView = Utils.findRequiredViewAsType(source, R.id.minimap_users_list, "field 'userListView'", RecyclerView.class);
  }

  @Override
  @CallSuper
  public void unbind() {
    NearbyPeopleMinimapFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.emptyView = null;
    target.userListView = null;
  }
}
