// View binding for ParcelInfoFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.search;

import android.view.View;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;
import com.lumiyaviewer.lumiya.ui.chat.ChatterPicView;
import com.lumiyaviewer.lumiya.ui.common.ImageAssetView;

public class ParcelInfoFragment_ViewBinding implements Unbinder {
  private ParcelInfoFragment target;

  private View view7f100258;

  private View view7f100250;

  @UiThread
  public ParcelInfoFragment_ViewBinding(final ParcelInfoFragment target, View source) {
    this.target = target;

    View view;
    target.parcelDetailsDescription = Utils.findRequiredViewAsType(source, R.id.parcel_details_desc, "field 'parcelDetailsDescription'", TextView.class);
    target.parcelDetailsName = Utils.findRequiredViewAsType(source, R.id.parcel_details_name, "field 'parcelDetailsName'", TextView.class);
    target.parcelImageView = Utils.findRequiredViewAsType(source, R.id.parcel_image_view, "field 'parcelImageView'", ImageAssetView.class);
    target.parcelLocation = Utils.findRequiredViewAsType(source, R.id.parcel_location, "field 'parcelLocation'", TextView.class);
    target.parcelOwnerName = Utils.findRequiredViewAsType(source, R.id.parcel_owner_name, "field 'parcelOwnerName'", TextView.class);
    target.parcelOwnerPic = Utils.findRequiredViewAsType(source, R.id.parcel_owner_pic, "field 'parcelOwnerPic'", ChatterPicView.class);
    target.parcelSimName = Utils.findRequiredViewAsType(source, R.id.parcel_sim_name, "field 'parcelSimName'", TextView.class);
    view = Utils.findRequiredView(source, R.id.parcel_owner_profile_button, "method 'onParcelOwnerProfileClick'");
    view7f100258 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onParcelOwnerProfileClick();
      }
    });
    view = Utils.findRequiredView(source, R.id.parcel_teleport_button, "method 'onParcelTeleportButton'");
    view7f100250 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onParcelTeleportButton();
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    ParcelInfoFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.parcelDetailsDescription = null;
    target.parcelDetailsName = null;
    target.parcelImageView = null;
    target.parcelLocation = null;
    target.parcelOwnerName = null;
    target.parcelOwnerPic = null;
    target.parcelSimName = null;

    view7f100258.setOnClickListener(null);
    view7f100258 = null;
    view7f100250.setOnClickListener(null);
    view7f100250 = null;
  }
}
