// View binding for SearchGridFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.search;

import android.view.KeyEvent;
import android.view.View;
import android.widget.EditText;
import android.widget.RadioGroup;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import androidx.recyclerview.widget.RecyclerView;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;

public class SearchGridFragment_ViewBinding implements Unbinder {
  private SearchGridFragment target;

  private View view7f100277;

  private View view7f100278;

  @UiThread
  public SearchGridFragment_ViewBinding(final SearchGridFragment target, View source) {
    this.target = target;

    View view;
    target.radioGroupSearchType = Utils.findRequiredViewAsType(source, R.id.radiogroup_search_type, "field 'radioGroupSearchType'", RadioGroup.class);
    target.searchResultsList = Utils.findRequiredViewAsType(source, R.id.search_results_list, "field 'searchResultsList'", RecyclerView.class);
    view = Utils.findRequiredView(source, R.id.search_string, "field 'searchString' and method 'onSearchTextAction'");
    target.searchString = Utils.castView(view, R.id.search_string, "field 'searchString'", EditText.class);
    view7f100277 = view;
    ((TextView) view).setOnEditorActionListener(new TextView.OnEditorActionListener() {
      @Override
      public boolean onEditorAction(TextView p0, int p1, KeyEvent p2) {
        return target.onSearchTextAction(p1, p2);
      }
    });
    view = Utils.findRequiredView(source, R.id.start_search_button, "method 'onSearchButtonClicked'");
    view7f100278 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onSearchButtonClicked();
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    SearchGridFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.radioGroupSearchType = null;
    target.searchResultsList = null;
    target.searchString = null;

    ((TextView) view7f100277).setOnEditorActionListener(null);
    view7f100277 = null;
    view7f100278.setOnClickListener(null);
    view7f100278 = null;
  }
}
