// View binding for MuteListFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.myava;

import android.view.View;
import android.widget.ListView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;

public class MuteListFragment_ViewBinding implements Unbinder {
  private MuteListFragment target;

  private View view7f1001e4;

  @UiThread
  public MuteListFragment_ViewBinding(final MuteListFragment target, View source) {
    this.target = target;

    View view;
    target.muteList = Utils.findRequiredViewAsType(source, R.id.muteList, "field 'muteList'", ListView.class);
    view = Utils.findRequiredView(source, R.id.add_mute_list_button, "method 'onAddMuteListButtonClick'");
    view7f1001e4 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onAddMuteListButtonClick();
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    MuteListFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.muteList = null;

    view7f1001e4.setOnClickListener(null);
    view7f1001e4 = null;
  }
}
