// View binding for MyAvatarFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.myava;

import android.view.View;
import android.widget.ListView;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;
import com.lumiyaviewer.lumiya.ui.chat.ChatterPicView;

public class MyAvatarFragment_ViewBinding implements Unbinder {
  private MyAvatarFragment target;

  @UiThread
  public MyAvatarFragment_ViewBinding(MyAvatarFragment target, View source) {
    this.target = target;

    target.myAvatarName = Utils.findRequiredViewAsType(source, R.id.my_avatar_name, "field 'myAvatarName'", TextView.class);
    target.myAvatarOptionsList = Utils.findRequiredViewAsType(source, R.id.my_ava_options_list, "field 'myAvatarOptionsList'", ListView.class);
    target.myAvatarPic = Utils.findRequiredViewAsType(source, R.id.my_avatar_pic, "field 'myAvatarPic'", ChatterPicView.class);
  }

  @Override
  @CallSuper
  public void unbind() {
    MyAvatarFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.myAvatarName = null;
    target.myAvatarOptionsList = null;
    target.myAvatarPic = null;
  }
}
