// View binding for TransactionLogFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.myava;

import android.view.View;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import androidx.recyclerview.widget.RecyclerView;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;
import com.lumiyaviewer.lumiya.ui.common.LoadingLayout;

public class TransactionLogFragment_ViewBinding implements Unbinder {
  private TransactionLogFragment target;

  @UiThread
  public TransactionLogFragment_ViewBinding(TransactionLogFragment target, View source) {
    this.target = target;

    target.loadingLayout = Utils.findRequiredViewAsType(source, R.id.loading_layout, "field 'loadingLayout'", LoadingLayout.class);
    target.transactionLogView = Utils.findRequiredViewAsType(source, R.id.transactionLogView, "field 'transactionLogView'", RecyclerView.class);
  }

  @Override
  @CallSuper
  public void unbind() {
    TransactionLogFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.loadingLayout = null;
    target.transactionLogView = null;
  }
}
