package com.lumiyaviewer.lumiya.ui.common.binding;

import androidx.annotation.UiThread;

/**
 * Releases the views a <code>*_ViewBinding</code> class bound: nulls the
 * target's view fields and removes the listeners it installed.
 *
 * <p>The <code>*_ViewBinding</code> classes were generated by ButterKnife
 * 10.2.3 and are now kept as source, so the library and its annotation
 * processor are no longer needed. Same contract as
 * <code>butterknife.Unbinder</code>.</p>
 */
public interface Unbinder {
    @UiThread
    void unbind();

    Unbinder EMPTY = () -> {
    };
}
