// View binding for GroupNoticeFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.chat;

import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;

public class GroupNoticeFragment_ViewBinding implements Unbinder {
  private GroupNoticeFragment target;

  private View view7f100177;

  private View view7f100179;

  @UiThread
  public GroupNoticeFragment_ViewBinding(final GroupNoticeFragment target, View source) {
    this.target = target;

    View view;
    view = Utils.findRequiredView(source, R.id.groupNoticeAttachmentButton, "field 'groupNoticeAttachmentButton' and method 'onGroupNoticeAttachmentButton'");
    target.groupNoticeAttachmentButton = Utils.castView(view, R.id.groupNoticeAttachmentButton, "field 'groupNoticeAttachmentButton'", Button.class);
    view7f100177 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onGroupNoticeAttachmentButton();
      }
    });
    target.groupNoticeAttachmentText = Utils.findRequiredViewAsType(source, R.id.groupNoticeAttachmentText, "field 'groupNoticeAttachmentText'", TextView.class);
    target.groupNoticeEditText = Utils.findRequiredViewAsType(source, R.id.groupNoticeEditText, "field 'groupNoticeEditText'", EditText.class);
    target.groupNoticeSubject = Utils.findRequiredViewAsType(source, R.id.groupNoticeSubject, "field 'groupNoticeSubject'", EditText.class);
    view = Utils.findRequiredView(source, R.id.groupNoticeSendButton, "method 'onGroupNoticeSendButton'");
    view7f100179 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onGroupNoticeSendButton();
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    GroupNoticeFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.groupNoticeAttachmentButton = null;
    target.groupNoticeAttachmentText = null;
    target.groupNoticeEditText = null;
    target.groupNoticeSubject = null;

    view7f100177.setOnClickListener(null);
    view7f100177 = null;
    view7f100179.setOnClickListener(null);
    view7f100179 = null;
  }
}
