// View binding for PayUserFragment, generated by ButterKnife 10.2.3 and kept as source
// so the app no longer needs ButterKnife. Edit by hand; see ui/common/binding.
package com.lumiyaviewer.lumiya.ui.chat;

import android.view.View;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.CallSuper;
import androidx.annotation.UiThread;
import com.lumiyaviewer.lumiya.ui.common.binding.Unbinder;
import com.lumiyaviewer.lumiya.ui.common.binding.DebouncingOnClickListener;
import com.lumiyaviewer.lumiya.ui.common.binding.Utils;
import com.lumiyaviewer.lumiya.R;

public class PayUserFragment_ViewBinding implements Unbinder {
  private PayUserFragment target;

  private View view7f100266;

  private View view7f10026a;

  @UiThread
  public PayUserFragment_ViewBinding(final PayUserFragment target, View source) {
    this.target = target;

    View view;
    target.payAmount = Utils.findRequiredViewAsType(source, R.id.pay_amount, "field 'payAmount'", EditText.class);
    target.payMessage = Utils.findRequiredViewAsType(source, R.id.user_pay_message, "field 'payMessage'", EditText.class);
    target.paymentDetailsBalance = Utils.findRequiredViewAsType(source, R.id.payment_details_balance, "field 'paymentDetailsBalance'", TextView.class);
    target.receivingUserName = Utils.findRequiredViewAsType(source, R.id.receiving_user_name, "field 'receivingUserName'", TextView.class);
    target.receivingUserPic = Utils.findRequiredViewAsType(source, R.id.receiving_user_pic, "field 'receivingUserPic'", ChatterPicView.class);
    view = Utils.findRequiredView(source, R.id.receiving_user_profile_button, "method 'onReceivingUserViewProfileClick'");
    view7f100266 = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onReceivingUserViewProfileClick();
      }
    });
    view = Utils.findRequiredView(source, R.id.user_pay_button, "method 'onUserPayButton'");
    view7f10026a = view;
    view.setOnClickListener(new DebouncingOnClickListener() {
      @Override
      public void doClick(View p0) {
        target.onUserPayButton();
      }
    });
  }

  @Override
  @CallSuper
  public void unbind() {
    PayUserFragment target = this.target;
    if (target == null) throw new IllegalStateException("Bindings already cleared.");
    this.target = null;

    target.payAmount = null;
    target.payMessage = null;
    target.paymentDetailsBalance = null;
    target.receivingUserName = null;
    target.receivingUserPic = null;

    view7f100266.setOnClickListener(null);
    view7f100266 = null;
    view7f10026a.setOnClickListener(null);
    view7f10026a = null;
  }
}
